### ISSUE TITLE
String not working for custom parameters

### ISSUE THREAD

**Issue by dragm83** [garethky/filaments-klipper-extra#3]
This plugin is exactly what I need and would like to use to manage my filaments. Great idea and great work.

I've tried assigning a custom property 'mesh' a string value of 'mesh2', for example, but it returns with "Unable to parse 'mesh2' as a Python literal". I've tried no quotes, single quotes and double quotes... Not sure if I'm just screwing up the syntax. 

![image](https://github.com/garethky/filaments-klipper-extra/assets/69442263/76c49e4f-9e2f-4e94-8af0-25006c06611a)

**Comment by garethky** [comment]
You have to use 2 sets of quotes and they have to be single and double quotes:

```
SETUP_FILAMENT NAME=PLA EXTRUDER=205 BED=60 MESH='"mesh2"'
```

Long explanation:

There are a number of klipper commands, particularly `SAVE_VARIABLE`, that [work the same way](https://github.com/Klipper3d/klipper/blob/master/docs/Command_Templates.md#save-variables-to-disk) and give the same error:

```
$ SAVE_VARIABLE VARIABLE=FOO VALUE=BAR
!! Unable to parse 'BAR' as a literal
$ SAVE_VARIABLE VARIABLE=FOO VALUE="BAR"
!! Unable to parse 'BAR' as a literal
$ SAVE_VARIABLE VARIABLE=FOO VALUE='"BAR"'
```

Quotes are optional in klipper commands. The command parser strips the first set of quotes from around the value and then the command tries to evaluate whats left as a python literal. Since the quotes are gone it says it doesn't recognize the bare characters as a string. We don't know that the type of "VALUE", or your "MESH", is definitively a string, so it cant be treated as a string. That's why `NAME=PLA` works, `NAME` is declared to only take a string value, so its actually cast directly to a string by the command parser, even if you make it a number or something else.

Would love to hear how you get on with the extension!

**Comment by dragm83** [comment]
Perfect, that worked! Thanks for the explanation.

Right now I'm using the extension to setup all of the helper functions (such as load filament, preheats, mesh leveling, etc.) and then just pass the filament Name from Cura's start g-code (or set it manually through macro buttons on Mainsail/Fluidd). My goal is basically to setup each filament and its parameters in Klipper, partly because Cura doesn't have per material Gcode where I can pass some custom settings easily and partly because I'd like it to be Slicer independent. 

Thanks again!
